// ... rest of the file ...
        const backendUrl = import.meta.env.VITE_API_URL || "http://localhost:8000";
        const res = await fetch(`${backendUrl}/s/${token}`);
// ... rest of the file ...
